### ISSUE TITLE
ResourceExhaustedError: OOM when allocating tensor with shape[860,2150,50] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

### ISSUE THREAD

**Issue by ramashka328** [seokhokang/graphvae_approx#2]
Hello,

Thank You for Your shared code. I am trying to run your it with the ZINC dataset you shared with default GVAE parameters and when I try to train the model following error appears:

`ResourceExhaustedError: OOM when allocating tensor with shape[860,2150,50] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc`

I am using computer with following parameters: NVIDIA GeForce GTX 1080 Ti GPU, 32 GB RAM. I am assuming these specifications should be enough for computations.

Python packages were installed using conda. Package versions:
cudatoolkit               10.0.130
cudnn                     7.6.5
keras                     2.3.1
numpy                     1.18.1
pandas                    1.0.1
python                    3.7.6
scikit-learn              0.22.1
tensorflow                1.14.0        
tensorflow-base           1.14.0     
tensorflow-estimator      1.14.0          
tensorflow-gpu            1.14.0

Maybe you have any idea what is the problem here? When I reduce dim_h to 25 the code runs perfectly.

**Comment by seokhokang** [comment]
That message appears when the gpu memory is not enough to run the code. I think you can try decreasing the batch size.
