### ISSUE TITLE
Getting latent space vectors

### ISSUE THREAD

**Issue by ramashka328** [seokhokang/graphvae_approx#3]
Hello,

I want to extract encoded latent vectors using your constructed model. Maybe You know how I can do this easily or should I rewrite the code?

Thank You.

**Comment by seokhokang** [comment]
"self.latent_mu" in MPNN.py corresponds to the encoded latent vector you want to extract.
You can get the vector by feeding input into self.node, self.edge, and self.property using the following code.

self.sess.run(self.latent_mu, feed_dict = {self.node: ?, self.edge:?, self.property:?})
