### ISSUE TITLE
Compared with GraphVAE

### ISSUE THREAD

**Issue by YeolYao** [seokhokang/graphvae_approx#5]
Hello, I am very interested in your paper, and I noticed that you've compared with the paper "GraphVAE: Towards Generation of Small Graphs Using Variational Autoencoders", can I find the implementation of this paper in your code? Thanks a lot~

**Comment by seokhokang** [comment]
Hi. You can find an implementation of GraphVAE at https://github.com/JiaxuanYou/graph-generation/tree/master/baselines/graphvae

**Comment by YeolYao** [comment]
Thanks a lot！
